// <auto-generated />
namespace _02_KT.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CreateFirstDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateFirstDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202301080741552_CreateFirstDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
